services:
  postgres:
    container_name: db
    hostname: postgres
    image: postgres:alpine
    env_file:
      - ./.postgres-env
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U educrm -d educrm" ]
      interval: 2s
      timeout: 1s
      retries: 5
    restart: always
