services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:alpine
    env_file:
      - ./.postgres-env
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U educrm -d educrm" ]
      interval: 2s
      timeout: 1s
      retries: 5
    restart: unless-stopped
  backend:
    container_name: backend
    hostname: backend
    image: ghcr.io/team-base64/edu-crm-backend-app:latest
    depends_on:
      - postgres
    env_file:
      - ./.backend-env
    ports:
      - 8080:8080
