DROP TABLE IF EXISTS "homeworks_tasks" CASCADE;

DROP TABLE IF EXISTS "tasks" CASCADE;

DROP TABLE IF EXISTS "students" CASCADE;

DROP TYPE IF EXISTS "social" CASCADE;

DROP TABLE IF EXISTS "messages" CASCADE;

DROP TABLE IF EXISTS "chats" CASCADE;

DROP TABLE IF EXISTS "calendars" CASCADE;

DROP TABLE IF EXISTS "teachers" CASCADE;

DROP TABLE IF EXISTS "classes" CASCADE;

DROP TABLE IF EXISTS "posts" CASCADE;

DROP TABLE IF EXISTS "homeworks" CASCADE;

DROP TABLE IF EXISTS "solutions" CASCADE;
