DROP TYPE IF EXISTS "SOCIAL" CASCADE;

DROP TABLE IF EXISTS "messages" CASCADE;

DROP TABLE IF EXISTS "chats" CASCADE;

DROP TABLE IF EXISTS "students" CASCADE;

DROP TABLE IF EXISTS "teachers" CASCADE;

DROP TABLE IF EXISTS "classes" CASCADE;

DROP TABLE IF EXISTS "classes_students" CASCADE;

DROP TABLE IF EXISTS "posts" CASCADE;

DROP TABLE IF EXISTS "homeworks" CASCADE;

DROP TABLE IF EXISTS "solutions" CASCADE;
