name: Deploy Postgres

on: push

env:
  DEPLOY_SRC: "sql"
  CONTAINER: "postgres"
  DATA_FILE: "*-data"

jobs:
  deploy:
    if: contains(github.event.head_commit.message, '[DEPLOY]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rlzav --delete"
          SOURCE: ${{ env.DEPLOY_SRC }}
          TARGET: ${{ secrets.TARGET_POSTGRES }}
      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd ${{ secrets.TARGET_DOCKER_COMPOSE }}
            echo '${{ secrets.POSTGRES_ENV }}' > ${{ vars.ENV_FILE_POSTGRES }}
            sed -i '/DRONE_SSH_PREV_COMMAND_EXIT_CODE/d' ${{ vars.ENV_FILE_POSTGRES }}
            sudo rm -rf ${{ env.DATA_FILE }}
            docker compose stop
            docker compose pull ${{ env.CONTAINER }}
            docker compose create ${{ env.CONTAINER }}
            docker compose start
            docker system prune -af --volumes
